### PR TITLE
[Fix #467]BUG:RPC cannot exit when illegal configuration starts

### LINKED ISSUE #467: [0.10.x]Qitmeer freezing at stopping server when the ip config is invalid
This issue only applies to 0.10.x, both cases work fine in 0.9.x

### build
0.10.0+dev-040005b

###  invalid  RPC IP
```
rpclisten=localhost:28131
```

Qitmeer displays error and tries to stop, yet failed and freezing
```
2021-04-06|19:17:28.761 [INFO ] Starting Rebroadcast                module=P2P
2021-04-06|19:17:28.761 [INFO ] try stop bm                         module=node
2021-04-06|19:17:28.761 [INFO ] Block manager shutting down         module=blkmanager
2021-04-06|19:17:28.761 [INFO ] Wait For Block manager stop ...     module=blkmanager
2021-04-06|19:17:28.761 [INFO ] Block manager stopped               module=blkmanager
2021-04-06|19:17:28.761 [INFO ] Stopping tx manager                 module=txmanager
2021-04-06|19:17:28.761 [INFO ] try stop cpu miner                  module=node
2021-04-06|19:17:28.761 [INFO ] P2P Service Stop                    module=P2P
2021-04-06|19:17:28.761 [INFO ] Rebroadcast shutting down           module=P2P
2021-04-06|19:17:28.761 [INFO ] Close BlockManager Event Subscribe  module=blkmanager
2021-04-06|19:17:28.761 [INFO ] P2P PeerSync Stop                   module=SYNC
2021-04-06|19:17:28.761 [ERROR] Uable to start server               error="'localhost' is not a valid IP address"
2021-04-06|19:17:28.761 [INFO ] Gracefully shutting down the server...
2021-04-06|19:17:28.761 [INFO ] Stopping Server                     module=node

```

Note:
Ctrl+C is not working

```
2021-04-06|19:17:28.761 [ERROR] Uable to start server               error="'localhost' is not a valid IP address"
2021-04-06|19:17:28.761 [INFO ] Gracefully shutting down the server...
2021-04-06|19:17:28.761 [INFO ] Stopping Server                     module=node
^C2021-04-06|19:21:05.031 [INFO ] Shutting down...                    Received signal=interrupt
^C2021-04-06|19:21:05.101 [INFO ] Already shutting down...            Received signal=interrupt
^C2021-04-06|19:21:05.557 [INFO ] Already shutting down...            Received signal=interrupt
^C2021-04-06|19:21:05.700 [INFO ] Already shutting down...            Received signal=interrupt
^C2021-04-06|19:21:06.083 [INFO ] Already shutting down...            Received signal=interrupt

```

### PR DESCRIPTION
**Pull request by lochjin**

### CODE REVIEW

**Comment by forchain** [comment]
not working on my machine, and the correct config is not working as well, please check

**Review by forchain — CHANGES_REQUESTED** [review]
not working on my machine, and the correct config is not working as well, please check

**Review by dindinw — CHANGES_REQUESTED** [review]
I think instead of change chan code, we can easily change the ```startRpc()``` method, and move the parseXXX() into the constructor of rpcServer, so that the error raised before the rpcServer instance has been created.

**Comment by lochjin** [comment]
> I think instead of changing `chan` code, we can easily change the `startRpc()` method, and move the parseXXX() into the constructor of rpcServer, so that the error raised before the rpcServer instance has been created.
> 
> ```go
> --- a/rpc/rpcserver.go
> +++ b/rpc/rpcserver.go
> @@ -125,6 +125,12 @@ func NewRPCServer(cfg *config.Config, events *event.Feed) (*RpcServer, error) {
>                 ReqStatus:              map[string]*RequestStatus{},
>         }
> 
> +       listeners, err := parseListeners(rpc.config, cfg.RPCListeners)
> +       if err != nil {
> +               return nil, err
> +       }
> +       rpc.listeners = listeners
> +
>         if cfg.RPCUser != "" && cfg.RPCPass != "" {
>                 login := cfg.RPCUser + ":" + cfg.RPCPass
>                 auth := "Basic " +
> @@ -140,7 +146,7 @@ func (s *RpcServer) Start() error {
>         if atomic.AddInt32(&s.run, 1) != 1 {
>                 return fmt.Errorf("Already running")
>         }
> -       err := s.startHTTP(s.config.RPCListeners)
> +       err := s.startHTTP()
>         if err != nil {
>                 return err
>         }
> @@ -183,7 +189,9 @@ const (
>         rpcAuthTimeoutSeconds = 10
>  )
> 
> -func (s *RpcServer) startHTTP(listenAddrs []string) error {
> +func (s *RpcServer) startHTTP() error {
> +
> +
> 
>         rpcServeMux := http.NewServeMux()
>         httpServer := &http.Server{
> @@ -236,12 +244,8 @@ func (s *RpcServer) startHTTP(listenAddrs []string) error {
>                 s.WebsocketHandler(ws, r.RemoteAddr, isAdmin)
>         })
> 
> -       listeners, err := parseListeners(s.config, listenAddrs)
> -       if err != nil {
> -               return err
> -       }
> -       s.listeners = listeners
> -       for _, listener := range listeners {
> +
> +       for _, listener := range s.listeners {
>                 s.wg.Add(1)
>                 go func(listener net.Listener) {
>                         log.Info(fmt.Sprintf("RPC server listening on addr:%v", listener.Addr()))
> ```

Yes, but the solution here is that you can't use your own chan when you stop

**Comment by dindinw** [comment]
> Yes, but the solution here is that you can't use your own chan when you stop:https://github.com/Qitmeer/qitmeer/pull/468/files#diff-d0070a6d63c684030189e4e74e021d42ed54686e999567c4156dc19db75c001eL67
Yes, you're correct, I think you can merge the suggestion with your original changes for a better solution.

**Review by dindinw — APPROVED** [review]

**Review by forchain — CHANGES_REQUESTED** [review]
please add such config to reproduce
 ···
 generate=1
 miningaddr=XmmELsPwPLvVrDwxSjREHdLWgZxmpMLRmEf
···

**Comment by dindinw** [comment]
> please add such config to reproduce
> ···
> generate=1
> miningaddr=XmmELsPwPLvVrDwxSjREHdLWgZxmpMLRmEf
> ···

@lochjin 
https://github.com/Qitmeer/qitmeer/blob/master/services/miner/cpuminer.go#L583
the `workerWg` keep waiting in this case.

**Comment by lochjin** [comment]
> > please add such config to reproduce
> > ···
> > generate=1
> > miningaddr=XmmELsPwPLvVrDwxSjREHdLWgZxmpMLRmEf
> > ···
> 
> @lochjin
> https://github.com/Qitmeer/qitmeer/blob/master/services/miner/cpuminer.go#L583
> the `workerWg` keep waiting in this case.

Yes, https://github.com/Qitmeer/qitmeer/issues/469

**Comment by lochjin** [comment]
> please add such config to reproduce
> ···
> generate=1
> miningaddr=XmmELsPwPLvVrDwxSjREHdLWgZxmpMLRmEf
> ···

https://github.com/Qitmeer/qitmeer/issues/469

**Pull request merged**
