### PR TITLE
add 162 block rewards & update testnet parameters

### PR DESCRIPTION
**Pull request by dindinw**
- add 162 blocks rewards to the genesis block
- add token destroy amount & list file hash to the genesis block
- update test parameters to adjust the block time to 15s
   * block time 30/2 = 15s
   * coin-base  reward 130/2 = 65
   * diff adjust 120*2 = 240
   * total reward block amount 3081353

### CODE REVIEW

**Comment by forchain** [comment]
so what is the purpose of halving the block interval, increase the concurrency?

**Comment by forchain** [comment]
@lochjin does this change need to update anti-cone size as well

**Comment by dindinw** [comment]
@forchain for a better confirm-time. The block order consistency works well under 0.8.1 & 0.8.1 test-net. I think we can move further on the 0.8.2.

**Comment by dindinw** [comment]
@lochjin please update the anti-cone size after the #187 merged.

**Pull request merged**
